package metier.PackageRecette;

/**
 * Enumeration de toutes les recettes du jeu
 */
public enum EnumRECETTES {
    
    // PATE, TOMATE, MOZZARELLA, JAMBON, CHAMPIGNON, PARMESAN
    PIZZA,
    // VIANDE, VIN, CHAMPIGNON, LARDON, CARROTTE, PATATE
    BOEUF_BOURGUIGNON,
    // PATATE, REBLOCHON, LARDON, OIGNON
    TARTIFLETTE,
    // JAMBON, BEURRE, PAIN, TOMATE
    SANDWICH,
    // OEUF, LARDON, CHAMPIGNON, EMMENTAL
    OMELETTE_COMPLETE,
    // JAMBON, EMMENTAL, OEUF, FARINE, OLIVE
    CAKE_SALE_AU_JAMBON,
    // SAUMON, CREME, CITRON, MOZZARELLA
    VERRINE_SAUMON,
    // PATE, BEURRE, SUCRE, CHOCOLAT
    COOKIE,
    // CHOCOLAT, BEURRE, FARINE, OEUF, SUCRE
    FONDANTS_AU_CHOCOLAT,
    // POMME, FARINE, SUCRE, BEURRE, CITRON
    CRUMBLE_AUX_POMMES,
    // FARINE, BEURRE, OEUF, CITRON, SUCRE
    TARTE_AUX_CITRONS,
    // VIANDE, CHAMPIGNON, OEUF, PATE, BEURRE
    BOEUF_WELLINGTON,
}