/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metier.PackageCarte;

/**
 *
 * @author antho
 */
public enum EnumBATIMENTS {
    MAISON,
    MAISON_HAUT,
    MAISON_BAS,
    MAISON_DROITE,
    MAISON_GAUCHE,
    MAISON_HAUT_BAS,
    MAISON_DROITE_GAUCHE,
    MAISON_HAUT_DROITE,
    MAISON_BAS_GAUCHE,
    MAISON_DROITE_BAS,
    MAISON_HAUT_GAUCHE,
    MAISON_DROITE_BAS_GAUCHE,
    MAISON_HAUT_DROITE_BAS,
    MAISON_HAUT_DROITE_GAUCHE,
    MAISON_HAUT_BAS_GAUCHE,
    MAISON_HAUT_DROITE_BAS_GAUCHE,
    
    MAGASIN,
    MAGASIN_HAUT,
    MAGASIN_BAS,
    MAGASIN_DROITE,
    MAGASIN_GAUCHE,
    MAGASIN_HAUT_BAS,
    MAGASIN_DROITE_GAUCHE,
    MAGASIN_HAUT_DROITE,
    MAGASIN_BAS_GAUCHE,
    MAGASIN_DROITE_BAS,
    MAGASIN_HAUT_GAUCHE,
    MAGASIN_DROITE_BAS_GAUCHE,
    MAGASIN_HAUT_DROITE_BAS,
    MAGASIN_HAUT_DROITE_GAUCHE,
    MAGASIN_HAUT_BAS_GAUCHE,
    MAGASIN_HAUT_DROITE_BAS_GAUCHE;
}
